// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(GitDbContext))]
    [Migration("20220913134608_fixEditorMode")]
    partial class fixEditorMode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Domain.EditorMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEditorModeActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EditorMode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEditorModeActive = true
                        });
                });

            modelBuilder.Entity("Domain.GitRepoInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathToFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToRunProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlToRepository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GitRepoInfo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathToFile = "C:\\Users\\rawci\\source\\repos\\",
                            PathToRunProgram = "C:\\Users\\rawci\\AppData\\Local\\Obsidian\\Obsidian.exe",
                            UrlToRepository = "https://github.com/RafalKedziora/test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
